"""
Comparison: our raw RSA implementation vs cryptography library (RSA-OAEP).

Both methods use the exact same key pair (n, e, d) generated by the library.
The goal is to show:
  - our impl:  raw RSA, chosen mode (ECB/CBC/CTR)  (m^e mod n per block)
  - library:   RSA-OAEP, probabilistic, padded      (random salt added)

Usage:
  python compare_rsa.py [image.png] [--mode ecb|cbc|ctr]
"""

import argparse
import os
from RSA import encrypt_png_file, decrypt_png_file, _parse_png_chunks
from rsa_library import (
    generate_keys_with_library,
    encrypt_png_file_library,
    decrypt_png_file_library,
)

_HERE    = os.path.dirname(os.path.abspath(__file__))
KEY_SIZE = 2048


def main():
    parser = argparse.ArgumentParser(
        description="Compare our raw RSA implementation with the cryptography library."
    )
    parser.add_argument(
        "input",
        nargs="?",
        default="png-beer.png",
        help="Input PNG file (default: png-beer.png)",
    )
    parser.add_argument(
        "--mode",
        choices=["ecb", "cbc", "ctr"],
        default="ecb",
        help="Block cipher mode for our RSA implementation (default: ecb)",
    )
    args = parser.parse_args()

    input_arg = args.input
    mode      = args.mode

    if os.path.isabs(input_arg):
        png_path = input_arg
    else:
        png_path = os.path.join(_HERE, input_arg)

    if not os.path.exists(png_path):
        print(f"[!] File not found: {png_path}")
        return

    stem    = os.path.splitext(os.path.basename(png_path))[0]
    our_enc = os.path.join(_HERE, f"{stem}_our_{mode}_encrypted.png")
    lib_enc = os.path.join(_HERE, f"{stem}_lib_encrypted.png")
    our_dec = os.path.join(_HERE, f"{stem}_our_{mode}_decrypted.png")
    lib_dec = os.path.join(_HERE, f"{stem}_lib_decrypted.png")

    PNG_PATH = png_path
    OUR_ENC  = our_enc
    LIB_ENC  = lib_enc
    OUR_DEC  = our_dec
    LIB_DEC  = lib_dec

    print(f"Input file : {PNG_PATH}")
    print(f"Our mode   : {mode.upper()}")

    # 1. Generate one key pair shared by both methods
    print("=" * 60)
    print("Generating RSA key pair (cryptography library)...")
    print("=" * 60)
    our_pub, our_priv, lib_pub, lib_priv = generate_keys_with_library(KEY_SIZE)

    with open(PNG_PATH, "rb") as f:
        original = f.read()

    # 2. Encrypt with our raw RSA (selected mode)
    print("\n" + "=" * 60)
    print(f"Encrypting with our implementation (raw RSA, {mode.upper()})...")
    print("=" * 60)
    encrypt_png_file(PNG_PATH, OUR_ENC, our_pub, mode=mode)

    # 3. Encrypt with library RSA-OAEP
    print("\n" + "=" * 60)
    print("Encrypting with cryptography library (RSA-OAEP)...")
    print("=" * 60)
    encrypt_png_file_library(PNG_PATH, LIB_ENC, lib_pub)

    # 4. Compare ciphertexts
    with open(OUR_ENC, "rb") as f:
        our_enc_data = f.read()
    with open(LIB_ENC, "rb") as f:
        lib_enc_data = f.read()

    our_idat = b"".join(cd for ct, cd in _parse_png_chunks(our_enc_data) if ct == b"IDAT")
    lib_idat = b"".join(cd for ct, cd in _parse_png_chunks(lib_enc_data) if ct == b"IDAT")
    orig_idat_len = len(b"".join(cd for ct, cd in _parse_png_chunks(original) if ct == b"IDAT"))

    print("\n" + "=" * 60)
    print("Comparison of encrypted IDAT (pixel) data")
    print("=" * 60)
    print(f"  Original IDAT size:                   {orig_idat_len:>10} bytes")
    print(f"  Our IDAT  (raw RSA, {mode.upper()}):           {len(our_idat):>10} bytes")
    print(f"  Library IDAT (RSA-OAEP):              {len(lib_idat):>10} bytes")
    print(f"  Ciphertexts are identical:            {our_idat == lib_idat}")
    print()
    print("  Why they differ:")
    print(f"  - Our raw RSA ({mode.upper()}): c = m^e mod n  (no OAEP padding, deterministic)")
    if mode == "ecb":
        print("    In ECB mode identical plaintext blocks produce identical ciphertext.")
        print("    This leaks patterns — image outlines may remain visible.")
    elif mode == "cbc":
        print("    In CBC mode each block is XORed with the previous ciphertext block.")
        print("    Patterns are hidden; identical blocks produce different ciphertext.")
    else:
        print("    In CTR mode a keystream is generated by encrypting a counter with RSA.")
        print("    Output looks random; identical blocks produce different ciphertext.")
    print()
    print("  - Library RSA-OAEP: before computing c = m^e mod n, OAEP mixes")
    print("    the plaintext with a random seed (SHA-256 based).")
    print("    Same plaintext -> completely different ciphertext every run.")
    print("    No patterns are visible; this is the standard secure usage of RSA.")

    # 5. Decrypt and verify
    print("\n" + "=" * 60)
    print("Decrypting both files...")
    print("=" * 60)
    decrypt_png_file(OUR_ENC, OUR_DEC, our_priv)
    decrypt_png_file_library(LIB_ENC, LIB_DEC, lib_priv)

    with open(OUR_DEC, "rb") as f:
        our_dec_data = f.read()
    with open(LIB_DEC, "rb") as f:
        lib_dec_data = f.read()

    print("\n" + "=" * 60)
    print("Verification")
    print("=" * 60)
    our_ok = our_dec_data == original
    lib_ok = lib_dec_data == original
    print(f"  Our decryption  == original: {'[✓]' if our_ok else '[✗] FAILED'}")
    print(f"  Lib decryption  == original: {'[✓]' if lib_ok else '[✗] FAILED'}")

    # 6. Output summary
    print("\n" + "=" * 60)
    print("Output files saved:")
    print("=" * 60)
    for path in [OUR_ENC, LIB_ENC, OUR_DEC, LIB_DEC]:
        print(f"  {path}")


if __name__ == "__main__":
    main()
